name: Sync and merge upstream repository
on:
  workflow_dispatch:
  schedule: 
  - cron: "0 21 * * *"

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Merge upstream
        run: |
          git config --global user.name 'dkile'
          git config --global user.email 'dkile532@naver.com'
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)
          git remote add upstream https://github.com/TEAM-LEG3ND/studium-fe.git
          git fetch upstream
          git switch dev
          git merge -Xtheirs upstream/dev
          git push origin dev
          # etc
